services:
  app-db:
    image: postgres:15
    container_name: app-db
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: mydb
    ports:
      - "127.0.0.1:5434:5432"  
    volumes:
      - app_db_data:/var/lib/postgresql/data

volumes:
  app_db_data: {}
